pod 'EAIntroView', '~> 2.8.0'
pod 'JTCalendar', '~> 2.0'
pod 'Realm'
pod 'Google/Analytics'
pod 'FrameAccessor'
pod 'MKFoundationKit', '~> 1.3'
pod "JazzHands"
pod 'RKDropdownAlert'
pod 'SCLAlertView-Objective-C'
pod 'UIColor-HexString'
pod 'Masonry'
